<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HPENVY" ignored="0" name="Default test" tests="13" failures="1" timestamp="03 Mar 2022 11:13:43 GMT" time="207.01" errors="0">
  <testcase name="firstCase" time="19.17" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="registrationpage" time="8.183" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="registration" time="25.11" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="verificationemail" time="13.804" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="nonactivated" time="16.562" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="invalidemail" time="15.541" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="invalidpassword" time="16.031" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="forgotpasswordpage" time="9.137" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="forgotpasswordnonregestired" time="23.72" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="forgotpasswordregisteredemail" time="12.57" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="forgotpasswordemail" time="15.063" classname="com.c6.TestCases.ImplementCases"/>
  <testcase name="resetpassword" time="21.292" classname="com.c6.TestCases.ImplementCases">
    <failure type="java.lang.AssertionError" message="expected [https://slic4rfe-ng-ngx.fabheads.in/login] but found [https://slic4rfe-ng-ngx.fabheads.in/forgot]">
      <![CDATA[java.lang.AssertionError: expected [https://slic4rfe-ng-ngx.fabheads.in/login] but found [https://slic4rfe-ng-ngx.fabheads.in/forgot]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.c6.TestCases.ImplementCases.resetpassword(ImplementCases.java:416)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- resetpassword -->
  <testcase name="login" time="9.705" classname="com.c6.TestCases.ImplementCases"/>
</testsuite> <!-- Default test -->
